sudo: required #Super user permissions
service:
  - docker #Installa docker

before_install: 
  - docker build -t fmalizia/docker-react -f Dockerfile.dev . #Taggo l'immagine secondo convenzione

script: #Tutti i comandi da avviare per il test, travis assume che il test esca in automatico
  #-e CI=true -> fa uscire docker dopo il test
  - docker run -e CI=true fmalizia/docker-react npm run test


deploy:
  provider: elasticbeanstalk #Preconfigurato in automatico in travis-ci
   #Recupero la regione da AWS
   #Docker-env.eba-7xppbe2z.us-east-1.elasticbeanstalk.com 
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-734674070325"
  bucket_path: "docker" #stesso nome dell'applicazione per default

  on:
    branch: master #FAi il deploy solo quando viene fatto un deploy sul branch master
  access_key_id: $AWS_ACCSS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"



#Non memorizzo qui le chiavi di accesso ma le metto tra le configurazioni di travis-ci
#AKIA2WDP4VM2TW6M5IUT

  #tfd2Lm/mLkLsmwDuy+zCKVm8XvLoxf8REDXIBwrP